export const GAME_LEVEL = {
    VERY_EASY: "VERY_EASY",
    EASY: "EASY",
    NORMAL: "NORMAL",
    HARD: "HARD",
    VERY_HARD: "VERY_HARD",
    IMPOSSIBLE: "IMPOSSIBLE"
}


export const GAME_STATUS = {
    PENDING: "PENDING",
    IN_PROGRESS: "IN_PROGRESS",
    FINISHED: "FINISHED"
}
