version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/app/src
    environment:
      PROJECT_NAME: 'Abstract User Service'
      PORT: 8080
      DB_CONN_STR: 'mongodb://db:27017/guesspionage?readPreference=primary&ssl=false'
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: 'http://localhost:8080/user-backend'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    depends_on:
      - server
  db:
    image: mongo:4.4.4-bionic
    environment:
      MONGO_INITDB_DATABASE: 'guesspionage'
    restart: always
    ports:
        - '27017:27017'
